version: '3.6'

services:
  #! ================================================================================================================
  php_service:
    container_name: shoes-php
    restart: always
    build:
      context: ./
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ./.env:/var/www/html/shoes/.env
      - ./app:/var/www/html/shoes
      - ./app/composer.json:/var/www/html/shoes/composer.json
    depends_on:
      - database_service
    networks:
      - shoes-network

  #! ================================================================================================================
  nginx_service:
    image: nginx:1.23.3
    container_name: shoes-nginx
    restart: always
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/conf.d:/etc/nginx/conf.d
      - ./app:/var/www/html/shoes
    ports:
      - ${PORT_NGINX_EXPOSE}:${PORT_NGINX_CONTAINER}
    depends_on:
      - php_service
      - database_service
    networks:
      - shoes-network

  #! ================================================================================================================
  database_service:
    image: mysql:8.0.32
    container_name: shoes-database
    restart: always
    environment:
      - MYSQL_ROOT_USER=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER =${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - .docker/data:/var/lib/mysql
      - .docker/database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "${PORT_DB_EXPOSE}:${PORT_DB_CONTAINER}"
    networks:
      - shoes-network

#! ================================================================================================================
networks:
  shoes-network:
    driver: bridge
